# Prefix
set -g prefix C-b

# Color
set -g default-terminal "screen-256color"

# Mouse
set -g mouse on

# Vi copy mode
set -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Pane split
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
